Add support for Bitbucket Server
PrefectHQ/prefect-bitbucket pull request #11
Opened 2023-02-16 19:19 UTC by sibbiii

Logging into Bitbucket cloud requires:

`"https://x-token-auth:{credential}@bitbucket.org/PrefectHQ/prefect.git"`

Logging into Bitbucket Server requires, _even if {credential} is the token and not the password !!_ 

`"https://{username}:{credential}@bitbucketserver.com/scm/projectname/teamsinspace.git"`

This behavior is documented here: https://confluence.atlassian.com/bitbucketserver/http-access-tokens-939515499.html and different to the cloud where a username is not allowed with a token and x-token-auth shall be used instead.

This pull request is to add support for Bitbucket Server. 
Closes #10 

Hope I've done all that is needed (sorry if not, i'm new here)
Sebastian

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-bitbucket/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-bitbucket/blob/main/CHANGELOG.md)

2023-02-16 19:27 UTC, ahuang11 requested changes
Thanks so much for contributing! The code looks good to me! Can you also an entry describing the changes in CHANGELOG.md, in the format of the other entries?

2023-02-16 19:27 UTC, ahuang11 commented on README.md
> +- For Bitbucket Server, set token and username.
```suggestion
!!! info "Differences between Bitbucket Server and Bitbucket Cloud"

For Bitbucket Cloud, only set the `token` to authenticate. For Bitbucket Server, set both the `token` and the `username`.
```

2023-02-16 19:31 UTC, sibbiii commented
> Thanks so much for contributing! The code looks good to me! Can you also an entry describing the changes in CHANGELOG.md, in the format of the other entries?

sure, just need to task switch quickly

2023-02-16 19:43 UTC, sibbiii commented
@ahuang11 Your !!! info update on readme.md does not work in Github, seems the !!! syntax is not supported. You can see the preview on https://github.com/sibbiii/prefect-bitbucket

2023-02-16 19:44 UTC, ahuang11 commented
Yep, that's fine, it should work on https://prefecthq.github.io/prefect-bitbucket.

2023-02-16 19:45 UTC, ahuang11 commented on README.md
> +For Bitbucket Cloud, only set the `token` to authenticate. For Bitbucket Server, set both the `token` and the `username`.
Forgot about indentation:

```suggestion
    For Bitbucket Cloud, only set the `token` to authenticate. For Bitbucket Server, set both the `token` and the `username`.
```

2023-02-16 19:54 UTC, sibbiii commented
now it looks even stranger

2023-02-16 19:56 UTC, ahuang11 commented
Thanks for revising! Eventually this repo will have a line up top "Visit the full docs [here](https://prefecthq.github.io/prefect-bitbucket) to see additional examples and the API reference."  that will redirect users to the main docs page, like in https://github.com/PrefectHQ/prefect-gcp

2023-02-16 19:58 UTC, sibbiii commented
> Thanks for revising! Eventually this repo will have a line up top "Visit the full docs [here](https://prefecthq.github.io/prefect-bitbucket) to see additional examples and the API reference." that will redirect users to the main docs page, like in https://github.com/PrefectHQ/prefect-gcp

The docs page may look fine, i cannot check that as its not updated yet, but in github the preview of the readme.md looks akward. see https://github.com/sibbiii/prefect-bitbucket

![image](https://user-images.githubusercontent.com/115080722/219473558-8e1cb3a7-cb70-46dc-96ff-9a3ac689e460.png)

2023-02-16 20:00 UTC, ahuang11 commented
Yeah, that's fine; will be adding this line in the README: "Visit the full docs [here](https://prefecthq.github.io/prefect-bitbucket) to see additional examples and the API reference" which I'm hoping to redirect users to the docs page.

If not, the awkward formatting can still attract attention to that info box.

2023-02-16 20:02 UTC, ahuang11 approved these changes

2023-02-16 20:36 UTC, sibbiii commented
![image](https://user-images.githubusercontent.com/115080722/219480422-12a61deb-3647-4aad-9e17-508c15a8cb24.png)

So, for an non pro it was really complicated to get mkdocs serve running. Needed some pips and could not deal with the unicode character in in readme.md that just crashes mkdocs serve

pip install mkdocs-gen-files
pip install mkdocstrings[python]
pip install mkdocs-material
# remove the unicode char in Feel free to ⭐ or watch - did not find a fix here 
mkdocs serve

Hope i've done now all thats needed

2023-02-16 20:38 UTC, ahuang11 commented
Thanks for the feedback! I believe `pip install -e ".[dev]" installs all those. I'll merge now

2023-02-16 20:38 UTC, merged

2023-02-16 20:40 UTC, sibbiii commented
> Thanks for the feedback! I believe `pip install -e ".[dev]" installs all those. I'll merge now

Reading the docs helps :-) The trickiest part was to find the unicode char, but anyhow, i managed it ...

2023-02-16 20:50 UTC, sibbiii commented
> Thanks for the feedback! I believe `pip install -e ".[dev]" installs all those. I'll merge now

![image](https://user-images.githubusercontent.com/115080722/219483422-4af6aaf9-6aac-48db-8d7d-830c3e2b6378.png)

@ahuang11 - i now followed the docs and made a fresh clone. mkdocs serve still fails in Windows if the unicode character is not removed, just as a note. Never mind, not really an issue ...

2023-02-16 21:46 UTC, ahuang11 commented
I believe it's the star. It'll be removed once I get around updating this collection. Thanks so much for contributing!

2023-02-17 07:24 UTC, sibbiii commented
> I believe it's the star. It'll be removed once I get around updating this collection. Thanks so much for contributing!

@ahuang11 
Sorry, I thought I wrote this: It is the star in "Feel free to ⭐️ or watch". I did not find a way around using mkdocs without removing it, and once removed, all worked. Maybe its also just an issue on windows or i missed a setting to deal with unicode characters.

The other thing you already know is the !!! info, it works fine in mkdocs, but breaks in the github review and the same on [PyPI](https://pypi.org/project/pip/)

And then there is one new thing I noticed after installing Version 0.1.1. There was also an update on the Bitbucket-Credentials. More fields were added that are currently unused in the Bitbucket block. But there is no broken functionality, just missing functionality (e.g. password) which is undocumented ...